### ISSUE TITLE
Allow caves to spawn items

### ISSUE THREAD

**Issue by vidia** [dschrag/DefinitelyNotDontStarve#5]
Create positions and chances to spawn items on given cave segments. 

Certain items need to be able to spawn throughout the map. In order to do this, we need two things: 

1. Locations for item spawns
2. Control for the random spawn chance

The locations will be easy and can at the least be a mesh on each cave section that can accept a spawn item. 

The control though needs to be decided. 

I am thinking some sort of priority list of spawns of given items. For example: 

A ladder must always be spawned for a given level of the cave (given there is no exit), so it spawns first, taking up one space. 

Then things like food, water, animals, etc can spawn in a priority order. 

This could be managed by a BP that can get all of the caves and their spawn points and randomly select things.

**Comment by vidia** [comment]
@dschrag What do you think of this method for spawning items? Should we still focus on this for Wednesday? 

I think getting item locations and maybe a BP that inserts random generic items might be a good goal personally.

**Comment by dschrag** [comment]
I think for our purposes that sounds like the best way to do it. Pick a random item spawn point -> Spawn ladder -> Pick another random item spawn point, have chance to spawn an item, have chance for item to be something else. Potentially we could make it so there's enough food for X minutes of making it through the level. That sounds like a plan.

**Comment by vidia** [comment]
It might be better to always spawn at least one food spot, but make it's quantity dependent on the overall size of the cave later on. 

Is there a good way to keep track of global variables in UE4? For things like the world size, number of caves, things like that.

**Comment by dschrag** [comment]
We can keep these variables in the level blueprint. Unless you want it stored even past going into the new cave. If you want that, then I think the GameMode? might be the place to put those.

**Comment by vidia** [comment]
Added to master. 

Caves will first spawn one of each item in the "Required Spawns" list on the ItemDistributer. Then there is a global random chance to spawn items from the optional list into the world at each location. 

Adding duplicates to those arrays will be the easiest way to handle spawning rates.
